---
- name: Sync NetBox Aruba devices to Zabbix
  hosts: all  # Targets all hosts from the AWX inventory
  gather_facts: false
  vars:
    # API Configuration
    zabbix_api_url: "{{ lookup('env', 'ZABBIX_API_URL') }}"
    zabbix_api_token: "{{ lookup('env', 'ZABBIX_API_TOKEN') }}"
    
    # Device Mapping Configuration
    role_to_template_mapping:
      "network-switch-edge-sw": 
        templateid: "952c106526d54ae281279f081f0cdf0f"
      "_default":
        templateid: "7e5eb5606bc4abba66c8b20381a1e8a"
    
    site_to_group_mapping:
      "tarpeena": "23"
      "_default": "1"
    
    zabbix_default_proxy: "SVRNMZB01"

  tasks:
    - name: Filter devices with 'zabbix' tag
      set_fact:
        zabbix_tagged_devices: |
          {{ 
            hostvars | dict2items 
            | selectattr('value.tags', 'defined') 
            | selectattr('value.tags', 'contains', 'zabbix') 
            | map(attribute='key') | list 
          }}
      run_once: true

    - name: Get Zabbix proxy ID (if proxy is configured)
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body: |
          {
            "jsonrpc": "2.0",
            "method": "proxy.get",
            "params": {
              "output": ["proxyid"],
              "filter": {"host": "{{ zabbix_default_proxy }}"}
            },
            "auth": "{{ zabbix_api_token }}",
            "id": 1
          }
      register: zabbix_proxy
      delegate_to: localhost
      run_once: true
      when: zabbix_default_proxy is defined

    - name: Create/update hosts in Zabbix (only for devices with zabbix tag)
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body: |
          {
            "jsonrpc": "2.0",
            "method": "host.create",
            "params": {
              "host": "{{ inventory_hostname }}",
              "interfaces": [{
                "type": 1,
                "main": 1,
                "useip": 1,
                "ip": "{{ hostvars[inventory_hostname].ansible_host }}",
                "dns": "",
                "port": "10050"
              }],
              "groups": [{
                "groupid": "{{ site_to_group_mapping[hostvars[inventory_hostname].site.slug] | default(site_to_group_mapping['_default']) }}"
              }],
              "templates": [{
                "templateid": "{{ role_to_template_mapping[hostvars[inventory_hostname].device_role.slug].templateid | default(role_to_template_mapping['_default'].templateid) }}"
              }]
              {% if zabbix_proxy is defined and zabbix_proxy.json.result %}
              ,"proxy_hostid": "{{ zabbix_proxy.json.result[0].proxyid }}"
              {% endif %}
            },
            "auth": "{{ zabbix_api_token }}",
            "id": 1
          }
      delegate_to: localhost
      when: 
        - inventory_hostname in zabbix_tagged_devices
        - hostvars[inventory_hostname].ansible_host is defined
      register: host_creation
      retries: 3
      delay: 5

    - name: Show creation results
      debug:
        msg: |
          Processed devices: {{ zabbix_tagged_devices | length }}
          Success: {{ host_creation.results | selectattr('failed', 'equalto', false) | list | length }}
          Failed: {{ host_creation.results | selectattr('failed') | list | length }}
      run_once: true