---
- name: Sync NetBox Aruba devices to Zabbix
  hosts: localhost  # Changed from "all:!localhost" since we're using API
  gather_facts: false
  vars:     
    role_to_template_mapping:
      "network-switch-edge-sw": 
        templateid: "952c106526d54ae281279f081f0cdf0f"
      "_default":
        templateid: "7e5eb5606bc4abba66c8b20381a1e8a"
    site_to_group_mapping:
      "tarpeena": "23"
      "_default": "1"
    debug:
    var: vars
  when: false  # Set to true when you want to see the output
  zabbix_default_proxy: "SVRNMZB01"

  tasks:
    - name: Authenticate to Zabbix API
      uri:
        url: '{{ ZABBIX_API }}'
        method: POST
        body_format: json
        body: |
          {
            "jsonrpc": "2.0",
            "method": "user.login",
            "params": {
              "user": '{{ ZABBIX_USER }}',
              "password": '{{ ZABBIX_PWORD }}'
            },
            "id": 1
          }
      register: zabbix_auth
      until: zabbix_auth.status_code == 200
      retries: 3
      delay: 5

    - name: Set auth token fact
      set_fact:
        zabbix_token: "{{ zabbix_auth.json.result }}"

    - name: Get proxy hostid
      uri:
        url: "{{ zabbix_api }}"
        method: POST
        headers:
           Content-Type: "application/json"
        body_format: json
        body: |
          {
            "jsonrpc": "2.0",
            "method": "proxy.get",
            "params": {
               "output": ["proxyid"],
               "filter": {"host": "{{ zabbix_default_proxy }}"}
           },
           "auth": "{{ zabbix_token }}",
           "id": 1
          }
      register: zabbix_proxy
      when: zabbix_default_proxy is defined

    - name: Get NetBox devices
      uri:
        url: "{{ NETBOX_API }}/api/dcim/devices/?limit=0&tag=zabbix"
        headers:
          Authorization: "Token {{ NETBOX_TOKEN }}"
        method: GET
        status_code: 200
      register: netbox_devices
      retries: 3
      delay: 5

    - name: Create hosts in Zabbix
      uri:
        url: '{{ ZABBIX_API }}'
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body: |
          {
            "jsonrpc": "2.0",
            "method": "host.create",
            "params": {
              "host": "{{ item.name }}",
              "interfaces": [{
                "type": 1,
                "main": 1,
                "useip": 1,
                "ip": "{{ item.primary_ip4.address.split('/')[0] }}",
                "dns": "",
                "port": "10050"
              }],
              "groups": [{
                "groupid": "{{ site_to_group_mapping[item.site.slug] | default(site_to_group_mapping['_default']) }}"
              }],
              "templates": [{
                "templateid": "{{ role_to_template_mapping[item.device_role.slug].templateid | default(role_to_template_mapping['_default'].templateid) }}"
              }],
              {% if zabbix_proxy is defined and zabbix_proxy.json.result %}
              "proxy_hostid": "{{ zabbix_proxy.json.result[0].proxyid }}"
              {% endif %}
            },
            "auth": "{{ zabbix_token }}",
            "id": 1
          }
      loop: "{{ netbox_devices.json.results }}"
      when: item.primary_ip4 is defined
      register: zabbix_host_creation
      ignore_errors: yes

    - name: Log failed creations
      debug:
        msg: "Failed to create {{ item.item.name }}: {{ item.msg }}"
      loop: "{{ zabbix_host_creation.results }}"
      when: item.failed

    - name: Logout from Zabbix API
      uri:
        url: '{{ ZABBIX_API }}'
        method: POST
        body:
          jsonrpc: "2.0"
          method: "user.logout"
          params: []
          auth: "{{ zabbix_token }}"
          id: 1
      when: zabbix_token is defined