---
- name: Sync NetBox Aruba devices to Zabbix
  hosts: all
  gather_facts: false
  vars:
    # API Configuration
    zabbix_api_url: "{{ lookup('env', 'ZABBIX_API_URL') }}"
    zabbix_api_token: "{{ lookup('env', 'ZABBIX_API_TOKEN') }}"
    
    # Device Mapping Configuration
    role_to_template_mapping:
      "network-switch-edge-sw": 
        templateid: "952c106526d54ae281279f081f0cdf0f"
      "_default":
        templateid: "7e5eb5606bc4abba66c8b20381a1e8a"
    
    site_to_group_mapping:
      "tarpeena": "23"
      "bell_bay": "22"
      "_default": "5"
    
    site_to_proxy_mapping:
      "22": "10633"    # Site ID 22 → Proxy ID 10633
      "23": "10761"    # Site ID 23 → Proxy ID 10761
      "_default": "10084"

  tasks:
    - name: Verify inventory data
      debug:
        msg: "Loaded {{ groups['all'] | length }} devices from inventory"
      run_once: true

    - name: Create/update hosts in Zabbix
      block:
        - name: Validate host data
          assert:
            that:
              - hostvars[inventory_hostname].ansible_host is defined
              - hostvars[inventory_hostname].site is defined
              - hostvars[inventory_hostname].device_role is defined
            fail_msg: "Missing required host variables for {{ inventory_hostname }}"
          when: "'zabbix' in (hostvars[inventory_hostname].tags | default([]))"

        - name: Create host in Zabbix
          uri:
            url: "{{ zabbix_api_url }}"
            method: POST
            headers:
              Content-Type: "application/json"
            body_format: json
            body: |
              {
                "jsonrpc": "2.0",
                "method": "host.create",
                "params": {
                  "host": "{{ inventory_hostname }}",
                  "interfaces": [{
                    "type": 1,
                    "main": 1,
                    "useip": 1,
                    "ip": "{{ hostvars[inventory_hostname].ansible_host }}",
                    "dns": "",
                    "port": "10050"
                  }],
                  "groups": [{
                    "groupid": "{{ site_to_group_mapping[hostvars[inventory_hostname].site.slug] | default(site_to_group_mapping['_default']) }}"
                  }],
                  "templates": [{
                    "templateid": "{{ role_to_template_mapping[hostvars[inventory_hostname].device_role.slug].templateid | default(role_to_template_mapping['_default'].templateid) }}"
                  }],
                  "proxy_hostid": "{{ site_to_proxy_mapping[hostvars[inventory_hostname].site.id | string] | default(site_to_proxy_mapping['_default']) }}"
                },
                "auth": "{{ zabbix_api_token }}",
                "id": 1
              }
            status_code: 200
            validate_certs: no
          delegate_to: localhost
          register: host_creation
          retries: 3
          delay: 5
          when: "'zabbix' in (hostvars[inventory_hostname].tags | default([]))"
      rescue:
        - name: Log creation error
          debug:
            msg: "Failed to process {{ inventory_hostname }}: {{ ansible_failed_result.msg }}"
          when: inventory_hostname is defined

    - name: Show summary results
      debug:
        msg: |
          Zabbix Sync Summary:
          Attempted devices: {{ host_creation.results | default([]) | length }}
          Successful: {{ host_creation.results | selectattr('failed', 'equalto', false) | list | length }}
          Failed: {{ host_creation.results | selectattr('failed') | list | length }}
      run_once: true