---
- name: Sync NetBox Aruba devices to Zabbix
  hosts: localhost
  gather_facts: false
  vars:

    # API Configuration
    zabbix_api_url: "{{ lookup('env', 'ZABBIX_API_URL') }}"
    zabbix_api_token: "{{ lookup('env', 'ZABBIX_API_TOKEN') }}"
    netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"

    # Device Mapping Configuration
    role_to_template_mapping:
      "network-switch-edge-sw": 
        templateid: "952c106526d54ae281279f081f0cdf0f"
      "_default":
        templateid: "7e5eb5606bc4abba66c8b20381a1e8a"
    
    site_to_group_mapping:
      "tarpeena": "23"
      "_default": "1"
    
    zabbix_default_proxy: "SVRNMZB01"

  tasks:
    - name: Get NetBox devices with 'zabbix' tag
      uri:
        url: "{{ netbox_url }}/dcim/devices/?tag=zabbix&platform__n=aoscx,aoscx_l2&status=active"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
        status_code: 200
      register: netbox_devices
      retries: 3
      delay: 5

    - name: Get Zabbix proxy ID (if proxy is configured)
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body: |
          {
            "jsonrpc": "2.0",
            "method": "proxy.get",
            "params": {
              "output": ["proxyid"],
              "filter": {"host": "{{ zabbix_default_proxy }}"}
            },
            "auth": "{{ zabbix_api_token }}",
            "id": 1
          }
      register: zabbix_proxy
      when: zabbix_default_proxy is defined

    - name: Create/update hosts in Zabbix
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body: |
          {
            "jsonrpc": "2.0",
            "method": "host.create",
            "params": {
              "host": "{{ item.name }}",
              "interfaces": [{
                "type": 1,
                "main": 1,
                "useip": 1,
                "ip": "{{ item.primary_ip4.address.split('/')[0] }}",
                "dns": "",
                "port": "10050"
              }],
              "groups": [{
                "groupid": "{{ site_to_group_mapping[item.site.slug] | default(site_to_group_mapping['_default']) }}"
              }],
              "templates": [{
                "templateid": "{{ role_to_template_mapping[item.device_role.slug].templateid | default(role_to_template_mapping['_default'].templateid) }}"
              }]
              {% if zabbix_proxy is defined and zabbix_proxy.json.result %}
              ,"proxy_hostid": "{{ zabbix_proxy.json.result[0].proxyid }}"
              {% endif %}
            },
            "auth": "{{ zabbix_api_token }}",
            "id": 1
          }
      loop: "{{ netbox_devices.json.results }}"
      when: item.primary_ip4 is defined
      register: host_creation
      retries: 3
      delay: 5

    - name: Show creation results
      debug:
        msg: |
          Processed {{ host_creation.results | length }} devices
          Success: {{ host_creation.results | selectattr('failed', 'equalto', false) | list | length }}
          Failed: {{ host_creation.results | selectattr('failed') | list | length }}