---
- name: Sync NetBox Aruba devices to Zabbix
  hosts: all  # Targets all hosts from the AWX inventory
  gather_facts: false
  vars:
    # API Configuration
    zabbix_api_url: "{{ lookup('env', 'ZABBIX_API_URL') }}"
    zabbix_api_token: "{{ lookup('env', 'ZABBIX_API_TOKEN') }}"
    
    # Device Mapping Configuration
    role_to_template_mapping:
      "network-switch-edge-sw": 
        templateid: "952c106526d54ae281279f081f0cdf0f"
      "_default":
        templateid: "7e5eb5606bc4abba66c8b20381a1e8a"
    
    site_to_group_mapping:
      "tarpeena": "23"
      "bell_bay": "22"
      "_default": "5"
    
    site_to_proxy_mapping:
      "22": "10633"    # Site ID 22 → Proxy ID 10633
      "23": "10761"    # Site ID 23 → Proxy ID 10761
      "_default": "10084"  # Default proxy ID

  tasks:
    - name: Filter devices with 'zabbix' tag
      set_fact:
        zabbix_tagged_devices: |
          {{ 
            hostvars | dict2items 
            | selectattr('value.tags', 'defined') 
            | selectattr('value.tags', 'contains', 'zabbix') 
            | map(attribute='key') | list 
          }}
      run_once: true

    - name: Process only zabbix-tagged devices
      when: "'zabbix' in (hostvars[inventory_hostname].tags | default([]))"

    - name: Create/update hosts in Zabbix with dynamic proxy assignment
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body: |
          {
            "jsonrpc": "2.0",
            "method": "host.create",
            "params": {
              "host": "{{ inventory_hostname }}",
              "interfaces": [{
                "type": 1,
                "main": 1,
                "useip": 1,
                "ip": "{{ hostvars[inventory_hostname].ansible_host }}",
                "dns": "",
                "port": "10050"
              }],
              "groups": [{
                "groupid": "{{ site_to_group_mapping[hostvars[inventory_hostname].site.slug] | default(site_to_group_mapping['_default']) }}"
              }],
              "templates": [{
                "templateid": "{{ role_to_template_mapping[hostvars[inventory_hostname].device_role.slug].templateid | default(role_to_template_mapping['_default'].templateid) }}"
              }],
              "proxy_hostid": "{{ site_to_proxy_mapping[hostvars[inventory_hostname].site_id | string] | default(site_to_proxy_mapping['_default']) }}"
              },
            "auth": "{{ zabbix_api_token }}",
            "id": 1
          }
      delegate_to: localhost
      when: 
        - inventory_hostname in zabbix_tagged_devices
        - hostvars[inventory_hostname].ansible_host is defined
      register: host_creation
      retries: 3
      delay: 5

    - name: Show creation results
      debug:
        msg: |
          Processed devices: {{ zabbix_tagged_devices | length }}
          Success: {{ host_creation.results | selectattr('failed', 'equalto', false) | list | length }}
          Failed: {{ host_creation.results | selectattr('failed') | list | length }}
      run_once: true