---
- name: Sync NetBox to Zabbix
  hosts: localhost
  gather_facts: false
  collections:
    - netbox.netbox
    - community.zabbix
    
  vars:
    netbox_url: "https://netbox.timberlinkaustralia.com.au/"
    zabbix_url: "https://itmonitor.timberlinkaustralia.com.au/zabbix/api_jsonrpc.php"
    zabbix_default_templates:
      - "Template OS Linux"
      - "Template Module ICMP Ping"
    device_role_mapping:
      server: "Linux Servers"
      switch: "Network Devices"
      router: "Network Devices"

  tasks:
    - name: Get all devices from NetBox
      community.netbox.netbox_device_module:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        filter:
          status: active
        api_version: "2.10"
      register: netbox_devices
      no_log: true

    - name: Create/Update Zabbix hosts
      community.zabbix.zabbix_host:
        server_url: "{{ zabbix_url }}"
        login_user: "{{ zabbix_user }}"
        login_password: "{{ zabbix_password }}"
        host_name: "{{ item.name }}"
        host_groups: 
          - name: "{{ device_role_mapping[item.device_role.slug] | default('Other Devices') }}"
        link_templates: "{{ zabbix_default_templates }}"
        interfaces:
          - type: 1  # Agent interface
            main: 1
            useip: 1
            ip: "{{ (item.primary_ip4.address | default('')).split('/')[0] }}"
            dns: ""
            port: "10050"
        tags:
          - tag: "source"
            value: "netbox"
          - tag: "site"
            value: "{{ item.site.slug }}"
        state: present
      loop: "{{ netbox_devices.devices }}"
      when: item.primary_ip4 is defined
      no_log: true