---
- name: Sync NetBox to Zabbix
  hosts: localhost
  gather_facts: false
  collections:
    - netbox.netbox
    - community.zabbix
    
  vars:
    netbox_url: "https://netbox.timberlinkaustralia.com.au/"
    zabbix_url: "https://itmonitor.timberlinkaustralia.com.au/zabbix/api_jsonrpc.php"
    zabbix_default_templates:
      - "Template OS Linux"
      - "Template Module ICMP Ping"
    device_role_mapping:
      server: "Linux Servers"
      switch: "Network Devices"
      router: "Network Devices"

  tasks:
    - name: Get active devices from NetBox
      netbox.netbox.nb_lookup:
        api_endpoint: "dcim/devices"
        api_filter:
          status: "active"
        api_token: "{{ netbox_token }}"
        validate_certs: false
      register: netbox_devices
      no_log: true

    - name: Create/Update Zabbix hosts
      community.zabbix.zabbix_host:
        server_url: "{{ zabbix_url }}"
        login_user: "{{ zabbix_user }}"
        login_password: "{{ zabbix_password }}"
        host_name: "{{ item.name }}"
        host_groups:
          - name: "{{ device_role_mapping[item.device_role.slug] | default('Other Devices') }}"
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ (item.primary_ip.address | default('')).split('/')[0] }}"
            port: "10050"
        state: present
      loop: "{{ netbox_devices.json }}"
      when: item.primary_ip is defined
      no_log: true